"""Point 2 — translate a set of flowcharts into a runnable multithreaded
Python program.

Design notes
------------
* Each flowchart becomes a thread function built as a *program-counter state
  machine*: ``while pc is not None: ... dispatch on pc``.  This represents an
  arbitrary directed graph (including cycles) directly, with no need to
  recover structured ``if``/``while`` constructs.
* Shared 32-bit variables live in one module-level dict ``MEM`` (shared
  memory, visible to every thread), initialised to 0.
* **Block-level atomicity.**  Every block executes while holding a single
  global ``LOCK``.  Threads can therefore only interleave *between* blocks —
  exactly the semantics the interpreter/tester use, so the generated program
  is a faithful realisation of the model.
* ``PRINT v`` writes ``str(v) + "\\n"``; ``INPUT v`` consumes the next
  whitespace-separated integer from stdin.  Output is compared elsewhere as a
  sequence of integer tokens, so spacing does not matter.
"""
from __future__ import annotations

from typing import List

from . import model as M


def _py_literal(b: M.Block) -> str:
    """Right-hand side of an ASSIGN, as Python referencing MEM."""
    if b.source_kind == M.SRC_VAR:
        return 'MEM[{!r}]'.format(b.source_var)
    return str(b.source_const)


def _dispatch_arm(fc: M.Flowchart, b: M.Block) -> List[str]:
    """The body of ``if pc == <id>:`` for one block (already inside LOCK)."""
    succ = fc.successors(b.id)
    lines: List[str] = []
    nxt = succ.get(None)
    if b.kind == M.START:
        lines.append("pc = {}".format(_goto(nxt)))
    elif b.kind == M.END:
        lines.append("pc = None")
    elif b.kind == M.ASSIGN:
        lines.append("MEM[{!r}] = {}".format(b.target, _py_literal(b)))
        lines.append("pc = {}".format(_goto(nxt)))
    elif b.kind == M.INPUT:
        lines.append("MEM[{!r}] = _read_int()".format(b.var))
        lines.append("pc = {}".format(_goto(nxt)))
    elif b.kind == M.PRINT:
        lines.append("_emit(MEM[{!r}])".format(b.var))
        lines.append("pc = {}".format(_goto(nxt)))
    elif b.kind == M.COND:
        op = "==" if b.cmp == M.CMP_EQ else "<"
        t = succ.get(True)
        f = succ.get(False)
        lines.append("if MEM[{!r}] {} {}:".format(b.var, op, b.const))
        lines.append("    pc = {}".format(_goto(t)))
        lines.append("else:")
        lines.append("    pc = {}".format(_goto(f)))
    return lines


def _goto(dst) -> str:
    return "None" if dst is None else str(dst)


def _thread_func(fc: M.Flowchart, index: int) -> List[str]:
    start = fc.start_block()
    start_id = start.id if start else None
    out: List[str] = []
    out.append("def thread_{}():  # {}".format(index, fc.name))
    out.append("    pc = {}".format(_goto(start_id)))
    out.append("    while pc is not None:")
    out.append("        with LOCK:")
    first = True
    # deterministic order for readability
    for b in sorted(fc.blocks.values(), key=lambda x: x.id):
        kw = "if" if first else "elif"
        first = False
        out.append("            {} pc == {}:  # {}".format(kw, b.id, b.label()))
        for line in _dispatch_arm(fc, b):
            out.append("                " + line)
    if first:  # no blocks at all
        out.append("            pc = None")
    else:
        out.append("            else:")
        out.append("                pc = None")
    out.append("")
    return out


HEADER = '''\
#!/usr/bin/env python3
"""Auto-generated by graph2Thread from a set of flowcharts.

{nthreads} thread(s), block-level atomicity via a single global lock.
Run:  python3 this_file.py  < input.txt
"""
import sys
import threading

# --- shared memory (all 32-bit int variables, visible to every thread) ---
MEM = {mem_init}

LOCK = threading.Lock()          # enforces block-level atomicity

# --- shared standard input, read as a stream of integers ---
_in_tokens = sys.stdin.read().split()
_in_pos = [0]


class BlockedOnInput(Exception):
    """INPUT had no value left.  In the flowchart model this is a *blocked*
    thread (a deadlock once nobody can move) rather than a crash -- such an
    execution produces no 'output after all threads finish', so we report it
    and exit non-zero instead of silently succeeding."""


def _read_int():
    """INPUT: consume the next whitespace-separated integer from stdin."""
    i = _in_pos[0]
    if i >= len(_in_tokens):
        raise BlockedOnInput("INPUT with no input remaining")
    _in_pos[0] = i + 1
    return int(_in_tokens[i])

def _emit(value):
    """PRINT: write one integer followed by a newline."""
    sys.stdout.write(str(value) + "\\n")

# collected per-thread failures (kept so the process can exit non-zero)
_ERRORS = []

def _run(fn, name):
    """Run one thread body, recording a blocked-on-input/deadlock or any other
    error instead of letting the thread die silently with exit code 0."""
    try:
        fn()
    except BlockedOnInput as ex:
        _ERRORS.append("thread '%s' deadlocked: %s" % (name, ex))
    except Exception as ex:  # pragma: no cover
        _ERRORS.append("thread '%s' failed: %s: %s" % (name, type(ex).__name__, ex))

'''

FOOTER = '''\
def main():
    threads = [{thread_list}]
    for t in threads:
        t.start()
    for t in threads:
        t.join()
    if _ERRORS:
        sys.stderr.write("Program did not complete normally:\\n")
        for _e in _ERRORS:
            sys.stderr.write("  " + _e + "\\n")
        sys.exit(1)

if __name__ == "__main__":
    main()
'''


def translate(project: M.Project) -> str:
    """Return runnable multithreaded Python source for ``project``.

    Assumes a structurally valid project (see :func:`model.validate_project`);
    the only thing guarded here is the degenerate empty-project case, which
    could otherwise emit a program with no threads."""
    if not project.flowcharts:
        raise ValueError("cannot translate a project with no threads (need 1..100)")
    variables = project.all_variables()
    mem_init = "{" + ", ".join("{!r}: 0".format(v) for v in variables) + "}"

    parts: List[str] = []
    parts.append(HEADER.format(nthreads=len(project.flowcharts), mem_init=mem_init))

    for i, fc in enumerate(project.flowcharts):
        parts.extend(_thread_func(fc, i))

    thread_list = ", ".join(
        "threading.Thread(target=_run, args=(thread_{}, {!r}))".format(
            i, fc.name or "thread_{}".format(i))
        for i, fc in enumerate(project.flowcharts)
    )
    parts.append(FOOTER.format(thread_list=thread_list))
    return "\n".join(parts)
